// <auto-generated />
using System;
using Enforcer.Modules.Analytics.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Enforcer.Modules.Analytics.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20251107110659_PrivateCounters")]
    partial class PrivateCounters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Analytics")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Enforcer.Modules.Analytics.Domain.ApiServiceStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveSubscribers")
                        .HasColumnType("int");

                    b.Property<Guid>("ApiServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageRating")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("FailedApiCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalApiCalls")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<float>("TotalResponseTimeMs")
                        .HasColumnType("real");

                    b.Property<int>("TotalSubscribers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApiServiceStats", "Analytics");
                });

            modelBuilder.Entity("Enforcer.Modules.Analytics.Domain.EndpointStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("FailedApiCalls")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalApiCalls")
                        .HasColumnType("bigint");

                    b.Property<float>("TotalResponseTimeMs")
                        .HasColumnType("real");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("_dailyCallCount")
                        .HasColumnType("bigint")
                        .HasColumnName("DailyCallCount");

                    b.Property<DateTime>("_dailyCountDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DailyCountDate");

                    b.HasKey("Id");

                    b.ToTable("EndpointStats", "Analytics");
                });

            modelBuilder.Entity("Enforcer.Modules.Analytics.Domain.PlanStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveSubscribers")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalSubscribers")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("_cancellationsThisMonth")
                        .HasColumnType("int")
                        .HasColumnName("CancellationsThisMonth");

                    b.Property<DateTime>("_monthTrackingDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MonthTrackingDate");

                    b.HasKey("Id");

                    b.ToTable("PlanStats", "Analytics");
                });

            modelBuilder.Entity("Enforcer.Modules.Analytics.Domain.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Value")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerId", "ApiServiceId")
                        .IsUnique();

                    b.ToTable("Ratings", "Analytics");
                });

            modelBuilder.Entity("Enforcer.Modules.Analytics.Domain.SubscriptionStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TotalApiCalls")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("_apiCallsUsedThisMonth")
                        .HasColumnType("bigint")
                        .HasColumnName("ApiCallsUsedThisMonth");

                    b.Property<DateTime>("_monthUsageDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("MonthUsageDate");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionStats", "Analytics");
                });
#pragma warning restore 612, 618
        }
    }
}
