/**
 * Enforcer API Contracts
 * This file is automatically generated from the OpenAPI specification.
 * Do not edit this file manually.
 */

// ============================================
// Data Schemas
// ============================================

export interface PagedResponse<T> {
  items: T[] | null;
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}

export enum RateLimitWindow {
  Second = 0,
  Minute = 1,
  Hour = 2,
}

export interface ApiServiceStatResponse {
  id: string;
  apiServiceId: string;
  totalApiCalls: number;
  successfulApiCalls: number;
  failedApiCalls: number;
  uptimePercentage: number;
  averageResponseTimeMs: number;
  activeSubscribers: number;
  totalSubscribers: number;
  averageRating: number;
  totalRatings: number;
}

export interface EndpointStatResponse {
  id: string;
  endpointId: string;
  totalApiCalls: number;
  successfulApiCalls: number;
  failedApiCalls: number;
  dailyCallCount: number;
  successRate: number;
  errorRate: number;
  averageResponseTimeMs: number;
}

export interface PlanStatResponse {
  id: string;
  planId: string;
  totalSubscribers: number;
  activeSubscribers: number;
  cancellationsThisMonth: number;
  cancellationPercentage: number;
}

export interface SubscriptionStatResponse {
  id: string;
  subscriptionId: string;
  totalApiCalls: number;
  apiCallsUsedThisMonth: number;
}

export interface RateApiServiceRequest {
  rating?: number;
}

export interface ApiKeyBanResponse {
  apiKey?: string;
  reason?: string;
  duration?: string;
  bannedAt: string;
  bannedBy: string;
}

export interface ApiServiceResponse {
  id: string;
  name?: string;
  description?: string;
  category?: string;
  serviceKey?: string;
  targetBaseUrl?: string;
  logoUrl?: string;
  isPublic: boolean;
  status?: string;
  apiDocId?: string;
  version?: string;
}

export interface ApiUsageResponse {
  id: string;
  subscriptionId: string;
  quotasLeft: number;
  overageUsed: number;
  resetAt: string;
}

export interface EndpointResponse {
  id: string;
  apiServiceId: string;
  planId: string;
  httpMethod?: string;
  publicPath?: string;
  targetPath?: string;
  rateLimit?: number;
  rateLimitWindow: RateLimitWindow;
  isActive: boolean;
}

export interface PlanResponse {
  id: string;
  apiServiceId: string;
  creatorId: string;
  name?: string;
  type?: string;
  priceInCents: number;
  billingPeriod?: string;
  quotaLimit: number;
  quotaResetPeriod?: string;
  rateLimit: number;
  rateLimitWindow: RateLimitWindow;
  features?: string[];
  overagePriceInCents?: number;
  maxOverage?: number;
  isActive: boolean;
  tierLevel: number;
}

export interface SubscriptionResponse {
  id: string;
  consumerId: string;
  planId: string;
  apiServiceId: string;
  apiKey?: string;
  subscribedAt: string;
  expiresAt?: string;
  isCanceled: boolean;
  plan: PlanResponse;
  apiUsage: ApiUsageResponse;
}

export interface BanApiKeyRequest {
  reason?: string;
  expiresAt?: string;
}

export interface CreateApiServiceRequest {
  name?: string;
  description?: string;
  category?: string;
  serviceKey?: string;
  targetBaseUrl?: string;
  logoUrl?: string;
  isPublic: boolean;
  status?: string;
}

export interface UpdateApiServiceRequest {
  name?: string;
  description?: string;
  category?: string;
  serviceKey?: string;
  targetBaseUrl?: string;
  logoUrl?: string;
  isPublic: boolean;
  status?: string;
  version?: string;
}

export interface EndpointCreationRequest {
  planId: string;
  httpMethod?: string;
  publicPath?: string;
  targetPath?: string;
  rateLimit?: number;
  rateLimitWindow?: string;
  isActive: boolean;
}

export interface CreateEndpointsRequest {
  endpoints?: EndpointCreationRequest[];
}

export interface UpdateEndpointRequest {
  planId: string;
  httpMethod?: string;
  publicPath?: string;
  targetPath?: string;
  rateLimit?: number;
  rateLimitWindow?: string;
  isActive: boolean;
}

export interface CreatePlanRequest {
  planType?: string;
  name?: string;
  priceInCents: number;
  billingPeriod?: string;
  quotaLimit: number;
  quotaResetPeriod?: string;
  rateLimit: number;
  rateLimitWindow?: string;
  features?: string[];
  overagePriceInCents?: number;
  maxOverage?: number;
  tierLevel: number;
}

export interface UpdatePlanRequest {
  planType?: string;
  name?: string;
  priceInCents: number;
  billingPeriod?: string;
  quotaLimit: number;
  quotaResetPeriod?: string;
  rateLimit: number;
  rateLimitWindow?: string;
  features?: string[];
  overagePriceInCents?: number;
  maxOverage?: number;
  tierLevel: number;
  isActive: boolean;
}

export interface CancelSubscriptionRequest {
  cancelImmediately: boolean;
}

export interface CreateSubscriptionRequest {
  apiServiceId: string;
  planId: string;
  promoCode?: string;
  returnUrl?: string;
}

export interface SwitchSubscriptionPlanRequest {
  targetPlanId: string;
}

export interface PaymentMethodResponse {
  id: string;
  type?: string;
  cardBrand?: string;
  cardLast4?: string;
  cardExpMonth?: number;
  cardExpYear?: number;
  isDefault: boolean;
  isActive: boolean;
  isVerified: boolean;
  billingAddress?: string;
  verifiedAt?: string;
  lastFailedAt?: string;
  lastFailureReason?: string;
  lastUsedAt?: string;
}

export interface PayoutResponse {
  payoutNumber?: string;
  creatorId: string;
  totalAmount: number;
  currency?: string;
  description?: string;
  status?: string;
  periodStart: string;
  periodEnd: string;
  scheduledDate: string;
  sentAt?: string;
  failureReason?: string;
}

export interface PromotionalCodeResponse {
  id: string;
  code?: string;
  type?: string;
  value: number;
  maxUses?: number;
  maxUsesPerUser?: number;
  usedCount: number;
  isActive: boolean;
  validFrom: string;
  validUntil?: string;
}

export interface SessionResponse {
  url?: string;
}

export interface WalletEntryResponse {
  id: string;
  walletId: string;
  type?: string;
  amount: number;
  currency?: string;
  referenceId?: string;
  description?: string;
  createdAt: string;
}

export interface WalletResponse {
  userId: string;
  balance: number;
  credits: number;
  lifetimeEarnings: number;
  currency?: string;
  lastPayoutAt?: string;
  isOnboardingComplete: boolean;
  isPayoutMethodConfigured: boolean;
}

export interface AddPaymentMethodRequest {
  returnUrl?: string;
}

export interface CreatePromotionalCodeRequest {
  apiServiceId: string;
  planId: string;
  code?: string;
  type?: string;
  value: number;
  maxUses?: number;
  maxUsesPerUser?: number;
  validFrom: string;
  validUntil?: string;
}

export interface GetPromotionalCodeRequest {
  planId: string;
}

export interface CreateOnboardingSessionRequest {
  returnUrl?: string;
}

export interface WithdrawFromWalletRequest {
  amount: number;
}

// ============================================
// API Endpoints
// ============================================

export const API_ENDPOINTS = {
  analytics: {
    getSubscriptionStat: {
      path: (subscriptionId: string) => `/api/subscriptions/${subscriptionId}/stats`,
      method: 'GET',
      // Request type: any
      // Response type: SubscriptionStatResponse
    },
    getPlanStat: {
      path: (planId: string) => `/api/plans/${planId}/stats`,
      method: 'GET',
      // Request type: any
      // Response type: PlanStatResponse
    },
    listEndpointStats: {
      path: '/api/analytics/endpoint-stats',
      method: 'GET',
      // Request type: any
      // Response type: EndpointStatResponse[]
    },
    getApiServiceStat: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/stats`,
      method: 'GET',
      // Request type: any
      // Response type: ApiServiceStatResponse
    },
    rateApiService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/rate`,
      method: 'POST',
      // Request type: RateApiServiceRequest
      // Response type: any
    },
  },
  apiKeyBans: {
    banApiKey: {
      path: (apiKey: string) => `/api/apikeys/${apiKey}/ban`,
      method: 'POST',
      // Request type: BanApiKeyRequest
      // Response type: any
    },
    unbanApiKey: {
      path: (apiKey: string) => `/api/apikeys/${apiKey}/ban`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    listBannedApiKeysByCreator: {
      path: '/api/apikeys/banned',
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<ApiKeyBanResponse>
    },
  },
  apiServices: {
    createApiService: {
      path: '/api/api-services',
      method: 'POST',
      // Request type: CreateApiServiceRequest
      // Response type: string
    },
    listApiServices: {
      path: '/api/api-services',
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<ApiServiceResponse>
    },
    deleteApiService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    getApiServiceById: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}`,
      method: 'GET',
      // Request type: any
      // Response type: ApiServiceResponse
    },
    updateApiService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}`,
      method: 'PUT',
      // Request type: UpdateApiServiceRequest
      // Response type: any
    },
    listCreatorApiServices: {
      path: (userId: string) => `/api/users/${userId}/api-services`,
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<ApiServiceResponse>
    },
  },
  apiUsages: {
    getSubscriptionApiUsage: {
      path: (subscriptionId: string) => `/api/subscriptions/${subscriptionId}/api-usage`,
      method: 'GET',
      // Request type: any
      // Response type: ApiUsageResponse
    },
  },
  endpoints: {
    createEndpoints: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/endpoints`,
      method: 'POST',
      // Request type: CreateEndpointsRequest
      // Response type: string[]
    },
    listEndpointsForService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/endpoints`,
      method: 'GET',
      // Request type: any
      // Response type: EndpointResponse[]
    },
    deleteEndpoint: {
      path: (endpointId: string) => `/api/endpoints/${endpointId}`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    getEndpointById: {
      path: (endpointId: string) => `/api/endpoints/${endpointId}`,
      method: 'GET',
      // Request type: any
      // Response type: EndpointResponse
    },
    updateEndpoint: {
      path: (endpointId: string) => `/api/endpoints/${endpointId}`,
      method: 'PUT',
      // Request type: UpdateEndpointRequest
      // Response type: any
    },
    listEndpointsForPlan: {
      path: (planId: string) => `/api/plans/${planId}/endpoints`,
      method: 'GET',
      // Request type: any
      // Response type: EndpointResponse[]
    },
  },
  paymentMethods: {
    addPaymentMethod: {
      path: '/api/payment-methods',
      method: 'POST',
      // Request type: AddPaymentMethodRequest
      // Response type: SessionResponse
    },
    listConsumerPaymentMethods: {
      path: '/api/payment-methods',
      method: 'GET',
      // Request type: any
      // Response type: PaymentMethodResponse[]
    },
    removePaymentMethod: {
      path: (paymentMethodId: string) => `/api/payment-methods/${paymentMethodId}`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    setDefaultPaymentMethod: {
      path: (paymentMethodId: string) => `/api/payment-methods/${paymentMethodId}/default`,
      method: 'PATCH',
      // Request type: any
      // Response type: any
    },
  },
  paymentProcessing: {
    createAccount: {
      path: '/api/stripe/create-account',
      method: 'POST',
      // Request type: any
      // Response type: any
    },
    deleteAccount: {
      path: (accountId: string) => `/api/stripe/delete-account${accountId}`,
      method: 'POST',
      // Request type: any
      // Response type: any
    },
    stripeWebhook: {
      path: '/api/payments/stripe/webhook',
      method: 'POST',
      // Request type: any
      // Response type: any
    },
  },
  payouts: {
    listPayoutsByCreator: {
      path: '/api/wallets/payouts',
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<PayoutResponse>
    },
  },
  plans: {
    createPlan: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/plans`,
      method: 'POST',
      // Request type: CreatePlanRequest
      // Response type: string
    },
    listPlansForService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/plans`,
      method: 'GET',
      // Request type: any
      // Response type: PlanResponse[]
    },
    deletePlan: {
      path: (planId: string) => `/api/plans/${planId}`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    getPlanById: {
      path: (planId: string) => `/api/plans/${planId}`,
      method: 'GET',
      // Request type: any
      // Response type: PlanResponse
    },
    updatePlan: {
      path: (planId: string) => `/api/plans/${planId}`,
      method: 'PUT',
      // Request type: UpdatePlanRequest
      // Response type: any
    },
  },
  promotionalCodes: {
    createPromotionalCode: {
      path: '/api/promo-codes',
      method: 'POST',
      // Request type: CreatePromotionalCodeRequest
      // Response type: any
    },
    deletePromotionalCode: {
      path: (promoCodeId: string) => `/api/promo-codes/${promoCodeId}`,
      method: 'DELETE',
      // Request type: any
      // Response type: any
    },
    getPromotionalCode: {
      path: (promoCode: string) => `/api/promo-codes/${promoCode}`,
      method: 'POST',
      // Request type: GetPromotionalCodeRequest
      // Response type: PromotionalCodeResponse
    },
    listPromotionalCodesByApiService: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/promo-codes`,
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<PromotionalCodeResponse>
    },
    listPromotionalCodesByPlan: {
      path: (planId: string) => `/api/promo-codes/${planId}`,
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<PromotionalCodeResponse>
    },
  },
  subscriptions: {
    cancelSubscription: {
      path: (subscriptionId: string) => `/api/subscriptions/${subscriptionId}/cancel`,
      method: 'PATCH',
      // Request type: CancelSubscriptionRequest
      // Response type: any
    },
    createSubscription: {
      path: '/api/subscriptions',
      method: 'POST',
      // Request type: CreateSubscriptionRequest
      // Response type: SessionResponse
    },
    listUserSubscriptions: {
      path: '/api/subscriptions',
      method: 'GET',
      // Request type: any
      // Response type: SubscriptionResponse[]
    },
    getSubscriptionById: {
      path: (subscriptionId: string) => `/api/subscriptions/${subscriptionId}`,
      method: 'GET',
      // Request type: any
      // Response type: SubscriptionResponse
    },
    listServiceSubscribers: {
      path: (apiServiceId: string) => `/api/api-services/${apiServiceId}/subscribers`,
      method: 'GET',
      // Request type: any
      // Response type: SubscriptionResponse[]
    },
    switchSubscriptionPlan: {
      path: (subscriptionId: string) => `/api/subscriptions/${subscriptionId}/switch-plan`,
      method: 'PATCH',
      // Request type: SwitchSubscriptionPlanRequest
      // Response type: any
    },
  },
  walletEntries: {
    listWalletEntriesByWallet: {
      path: '/api/wallets/entries',
      method: 'GET',
      // Request type: any
      // Response type: PagedResponse<WalletEntryResponse>
    },
  },
  wallets: {
    createOnboardingSession: {
      path: '/api/wallets/onboarding-session',
      method: 'POST',
      // Request type: CreateOnboardingSessionRequest
      // Response type: SessionResponse
    },
    getWalletByUser: {
      path: '/api/wallets',
      method: 'GET',
      // Request type: any
      // Response type: WalletResponse
    },
    withdrawFromWallet: {
      path: '/api/wallets/withdraw',
      method: 'POST',
      // Request type: WithdrawFromWalletRequest
      // Response type: any
    },
  },
} as const;

export type ApiEndpoints = typeof API_ENDPOINTS;
