<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Enforcer.Common.Infrastructure\Enforcer.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Common\Enforcer.Common.Presentation\Enforcer.Common.Presentation.csproj" />
    <ProjectReference Include="..\Enforcer.Modules.Users.Application\Enforcer.Modules.Users.Application.csproj" />
  </ItemGroup>

</Project>
